version: '3'

services:
  api:
    container_name: api-country
    restart: always
    build: .
    ports:
      - "4000:8080"
    links:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27022:27017"
